### ISSUE TITLE
Add workaround for https://github.com/vbpf/ebpf-verifier/issues/427

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows-demo#35]
https://github.com/vbpf/ebpf-verifier/issues/427 causes bpf_printk to be unusable. Until this is fixed the bpf_printk in https://github.com/microsoft/ebpf-for-windows-demo/blob/main/connection_tracker/bpf/conn_track.c#L43 needs to be disabled.

**Comment by dthaler** [comment]
https://github.com/vbpf/ebpf-verifier/pull/459 will address this if/when it is merged.

**Comment by dthaler** [comment]
This is fixed in the verifier, so closing this issue.
